name: spark
version: ${project.version}
description: ${project.description}
authors: [Luck, sk89q]
main: me.lucko.spark.bukkit.SparkBukkitPlugin

commands:
  profiler:
    description: Main plugin command