name: spark
version: 1.0.2
description: ${project.description}
authors: [Luck, sk89q]
main: me.lucko.spark.bukkit.SparkBukkitPlugin

commands:
  spark:
    description: Main plugin command
    aliases: [profiler]